[BitTorrent]
Session\DefaultSavePath=/data/torrents
Session\Port=14671
Session\QueueingSystemEnabled=false
Session\SSL\Port=15282

[Meta]
MigrationVersion=8

[Preferences]
Downloads\SavePath=/data/torrents
WebUI\AuthSubnetWhitelist=172.16.0.0/12, 192.168.0.0/16, 10.0.0.0/8, 127.0.0.1/32
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(Qv5JSRorN0zF+ICs/+ZuQacE+h6IzfelXOWnEIj+n+gfnZfzL27XT+0byTDdtOapQhNZckvFp/hUL67c9t0avCy6BFaFXNkE3UMex/etBzs=)"
